version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 5 
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "tony-yun" 
    assignees:
      - "tony-yun" 
    ignore:
      - dependency-name: ""
        versions: [""]
    rebase-strategy: "auto" 
